#!/system/bin/sh
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
	echo "Modifying read_ahead_kb parameters"
		echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb
    else
        echo "read_ahead_kb not found"
fi

# Optimize SQlite databases of apps
for i in \
`find /data -iname "*.db"`; 
do \
	sqlite3 $i 'VACUUM;'; 
done;
