#!/system/bin/sh
#

# network security related settings

# Ignore all kinds of icmp packets or pings

echo 1 >  /proc/sys/net/ipv4/icmp_echo_ignore_all # default: 0

# Some routers send invalid responses to broadcast frames, and each one generates a
# warning that is logged by the kernel. These responses can be ignored:

echo 1 >  /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses

# When the server is heavily loaded or has many clients with bad connections with high
# latency, it can result in an increase in half-open connections. This is common for Web
# servers, especially when there are a lot of dial-up users. These half-open connections are
# stored in the backlog connections queue. You should set this value to at least 4096. (The
# default is 1024.)
# Setting this value is useful even if your server does not receive this kind of connection,
# because it can still be protected from a DoS (syn-flood) attack.

echo 4096 > /proc/sys/net/ipv4/tcp_max_syn_backlog # default: 128

echo 2 > /proc/sys/net/ipv4/tcp_synack_retries # default: 5

# Increase the number of outstanding syn requests allowed.
# Note: some people (including myself) have used tcp_syncookies to handle the problem of too many legitimate outstanding SYNs. 

echo 2500 > /proc/sys/net/core/netdev_max_backlog # default: 1000
echo 1 > /proc/sys/net/ipv4/tcp_window_scaling # default

echo 1 > /proc/sys/net/ipv4/tcp_window_scaling # default

# disable IP dynaddr
echo 0 > /proc/sys/net/ipv4/ip_dynaddr # default
